# qwen3-8b-infer-lora.yaml
### model
model_name_or_path: Qwen/Qwen3-8B-Instruct-2507
adapter_name_or_path: saves/qwen3-8b/lora/meta-attack-v2
trust_remote_code: true

### template
template: qwen3_nothink

### inference
finetuning_type: lora
infer_backend: huggingface
infer_dtype: bfloat16
max_new_tokens: 512
temperature: 0.7
top_p: 0.9
top_k: 50
repetition_penalty: 1.05
do_sample: true
